kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: node-service
  image: golang
  commands:
  - go build
  - go test
  when:
    branch:
    - master
- name: build
  image: plugins/docker
    repo: gaamaro/node-service
    username: gaamaro
    password: "@Hqiq00vx"
    when:
      branch: master